Ku 2
tungatarovKl/ku1-newsletter-messenger pull request #2
Opened 2022-11-12 13:03 UTC by DKBdg

2022-11-12 13:08 UTC, tungatarovKl approved these changes

2022-11-12 13:08 UTC, tungatarovKl commented on cmd/api/main.go
> +
пустая строка

2022-11-12 13:57 UTC, KornilovVl requested changes

2022-11-12 13:57 UTC, KornilovVl commented on cmd/api/main.go
> +		log.Fatalf("Ошибка декодирования файла конфигов %v", err)
Я бы добавил проверку на пустые поля в структуре после чтения конфигов

2022-11-12 15:48 UTC, tungatarovKl commented on cmd/api/main.go
> +		log.Fatalf("Ошибка декодирования файла конфигов %v", err)
не критично)

2022-11-13 04:35 UTC, tungatarovKl commented
ребята, давайте не будем затягивать с docker. Если не получается, давайте добавим позже @DKBdg @KornilovVl

2022-11-13 06:10 UTC, DKBdg commented on cmd/api/main.go
> +		log.Fatalf("Ошибка декодирования файла конфигов %v", err)
я бы сейчас не добавлял , потому что bottoken сейчас априори пустой (а его нужно железно проверять). Я считаю, что это можно добавить в последующем развитии проекта. Плюс ко всему, он вероятнее всего выдаст ошибку подключения к DB при присутствии пустых полей, поэтому не вижу смысла это дописывать пока что.

2022-11-13 06:19 UTC, DKBdg commented on cmd/api/main.go
> +		log.Fatalf("Ошибка декодирования файла конфигов %v", err)
Но я добавлю раз просьба поступила.)

2022-11-13 06:33 UTC, tungatarovKl approved these changes

2022-11-13 06:36 UTC, merged