Ku 4- создал телеграм бота, добавил сохранение пользователей в БД, добавил обработку команды /start, поднял проект в докере
tungatarovKl/ku1-newsletter-messenger pull request #3
Opened 2022-11-13 15:29 UTC by KornilovVl

Создал телеграм- бота
Добавил функционал сохранения пользователей в БД
Добавил обработку команды /start из телеграм-бота
Добавил миграцию для БД
Добавил функицию чтения конфига чтоб уменьшить количество дублирующегося кода
Настроил поднятие проекта в Docker

2022-11-13 15:31 UTC, KornilovVl commented
![](https://github.trello.services/images/mini-trello-icon.png) [KU-4 Подключить бота в микросервис](https://trello.com/c/adouqOIx/7-ku-4-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C-%D0%B1%D0%BE%D1%82%D0%B0-%D0%B2-%D0%BC%D0%B8%D0%BA%D1%80%D0%BE%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81)

2022-11-13 16:38 UTC, tungatarovKl requested changes

2022-11-13 16:38 UTC, tungatarovKl commented on cmd/bot/main.go
> +	println("BOT")
дебаг инфо

2022-11-13 16:38 UTC, tungatarovKl commented on cmd/bot/main.go
> +	tgBot := Bot.Bot{
нужно добавить пустую строку

2022-11-13 16:38 UTC, tungatarovKl commented on cmd/bot/main.go
> +	tgBot.Bot.Handle("/start", tgBot.StartHandler)
нужно добавить пустую строку

2022-11-13 16:38 UTC, tungatarovKl commented on internal/models/migrations/CreateUsersTable.go
> +package main
использовать package main не в main вводить в заблуждение

2022-11-13 17:10 UTC, tungatarovKl approved these changes

2022-11-13 18:08 UTC, DKBdg commented on config/ConfigReader.go
> +		log.Fatal("Error decoding config: ", configPath, err.Error())
Если придираться , я бы перевел все ошибки либо на русский, либо целиком на английский. (Это , конечно, можно сделать когда мы потом будем в конце шлифовать код)

2022-11-13 18:08 UTC, DKBdg commented on config/ConfigReader.go
> +		cfg.DbPassword == "" ||
Если не ошибаюсь, бывают моменты, когда пароль равен "". Тогда это не совсем будет работать (По моему эту ошибку породил еще мой коммит)

2022-11-14 05:16 UTC, tungatarovKl approved these changes

2022-11-14 05:24 UTC, merged