KU-6 Добавить проверку токенов который приходят вместе с запросами в микросервис go
tungatarovKl/ku1-newsletter-messenger pull request #5
Opened 2022-11-15 19:57 UTC by DKBdg

2022-11-16 03:21 UTC, tungatarovKl requested changes

2022-11-16 03:21 UTC, tungatarovKl commented on internal/models/Token.go
> +
пустая строка

2022-11-16 03:21 UTC, tungatarovKl commented on internal/controllers/NewsletterController.go
> +		for _, user := range users {
строка между loop и sendWG

2022-11-16 03:21 UTC, tungatarovKl commented on internal/controllers/NewsletterController.go
> +			//New routine
не нужный коммент

2022-11-16 03:21 UTC, tungatarovKl commented on internal/controllers/NewsletterController.go
> +		//Waiting for all routines to complete
не нужный коммент

2022-11-16 03:21 UTC, tungatarovKl commented on internal/controllers/NewsletterController.go
> +		if bot.Database.CheckToken(apiRequest.Token) == nil {
не понял логику. Т.е если не возвращается ошибка (error == nil), мы не пропускаем?

2022-11-16 10:12 UTC, KornilovVl requested changes

2022-11-16 10:12 UTC, KornilovVl commented on build/DatabaseCreation.sql
> +CREATE TABLE `tokens` (
Давай добавим еще колонку с названием сервиса для которого этот токен.
Когда будет несколько токенов, уже сложно будет найти нужный

2022-11-16 10:12 UTC, KornilovVl commented on build/DatabaseCreation.sql
> +  `Token_String` varchar(150) UNIQUE NOT NULL
Предлагаю для большей информативности назвать колонку просто Token. "String" имхо вводит в заблуждение и сеет неясность

2022-11-16 10:12 UTC, KornilovVl commented on build/DatabaseCreation.sql
> +CREATE TABLE `tokens` (
Или не название сервиса, а название токена.

2022-11-16 10:12 UTC, KornilovVl commented on build/DatabaseCreation.sql
> +  `Token_String` varchar(150) UNIQUE NOT NULL
И если добавить еще 1 колонку для название токена\сервиса, то предлагаю ее назвать Service_Name или Token_Name соответственно

2022-11-16 10:12 UTC, KornilovVl commented on internal/models/Token.go
> +	return currentToken.Error
Лучше переписать проверку токена более очевидным путем, например if resultToken.Token == "" return false

2022-11-16 10:12 UTC, KornilovVl commented on internal/models/Token.go
> +func (database *Database) CheckToken(tokenStr string) error {
Если идти по совпадению названия функции и возвращаемого значения, то (глядя на следующий коммент к возвращаемому значению), я бы назвал эту функцию ValidateToken

2022-11-16 10:12 UTC, KornilovVl commented on internal/models/Token.go
> +	var resultToken Token
Чекнул дебагом, структура не заполняется

2022-11-16 10:12 UTC, KornilovVl commented on config/local.toml
>  #Telegram bot token
Можно не коммитить изменения паролей и токенов при локальном тесте, если они не влияют на разработку тиммейта

2022-11-16 10:12 UTC, KornilovVl commented on build/docker-compose.yml
> +            MYSQL_PASSWORD: 1234
Можно не коммитить изменения паролей и токенов при локальном тесте, если они не влияют на разработку тиммейта

2022-11-16 10:12 UTC, KornilovVl commented on internal/controllers/NewsletterController.go
> +			http.Error(rw, "Invalid token entered", http.StatusBadRequest)
При любом значении токена возвращает "ОК" со статусом 200

2022-11-16 16:23 UTC, DKBdg commented on internal/controllers/NewsletterController.go
> +		if bot.Database.CheckToken(apiRequest.Token) == nil {
ошибся

2022-11-17 04:44 UTC, KornilovVl requested changes

2022-11-17 04:44 UTC, KornilovVl commented on internal/controllers/NewsletterController.go
> +				http.Error(rw, err.Error(), http.StatusBadRequest)
Т.к. тело респонса отображается в админке, лучше не отправлять туда полный текст ошибки.
Давай сделаем такой же текст ошибки, как при ошибке получения юзеров из БД:
http.Error(rw, "Dependency error", http.StatusFailedDependency)

2022-11-17 04:44 UTC, KornilovVl commented on internal/controllers/NewsletterController.go
> +				http.Error(rw, err.Error(), http.StatusBadRequest)
Ошибка не может произойти по вине пользователя и является системным сбоем, поэтому давай ее залогируем с выводом полного текста ошибки (так же как при получении юзеров из БД)

2022-11-17 04:44 UTC, KornilovVl commented on internal/controllers/NewsletterController.go
> +		if checked, err := bot.Database.ValidateToken(apiRequest.Token); checked == false {
У нас на одном уровне вложенности обрабатывается несколько ошибок. Давай сделаем ей уникальное имя, например vtErr (сокращение от Validate Token Error), чтоб в будущем не возникло конфликта названий и было четко видно что это за ошибка и откуда она взялась

2022-11-17 04:44 UTC, KornilovVl commented on internal/models/Token.go
> +	if tokenStr == "" {
Предлагаю дополнительно добавить проверку на пустой токен перед вызовом этой функции в контроллере.
Это уменьшит количество кода, через которое нужно пройти реквесту чтобы обнаружить невалидные данные.
Так же при использовании описанного варианта мы сможем задавать текст ошибки в самом контроллере, например
http.Error(rw, "Authentication error", http.StatusNetworkAuthenticationRequired)

2022-11-17 04:53 UTC, tungatarovKl requested changes

2022-11-17 04:53 UTC, tungatarovKl commented on internal/controllers/NewsletterController.go
> +		if checked, err := bot.Database.ValidateToken(apiRequest.Token); checked == false {
обычно всегда используется одна переменная. Не вижу пользы от создания разных переменных. Если для логов, то, обычно всегда логируется сразу после ошибки и соответственно всегда err будет равен последней ошибке

2022-11-17 06:31 UTC, KornilovVl reviewed
А что за файлик /build/Vladimir ?

2022-11-17 06:52 UTC, KornilovVl requested changes

2022-11-17 06:52 UTC, KornilovVl commented on internal/controllers/NewsletterController.go
> -		sendWG.Add(len(users))
Нужная строчка, не знаю зачем ты ее удалил)

2022-11-17 06:52 UTC, KornilovVl commented on internal/models/Token.go
> +	err := database.Connection.Model(Token{Token_Key: tokenStr}).Count(&result).Error
Проверь, пожалуйста, еще раз. У меня выдает общее количество записей в БД, а не количество записей с нужным токеном.
Как пример можешь рабочего фильтра посмотреть на функцию NewUser:
	dbFind := database.Connection.Find(&User{}, "Telegram_Id = ?", telegramId)

2022-11-17 12:32 UTC, DKBdg commented
> А что за файлик /build/Vladimir ?

idk, файл уже был там, когда поднимал проект

2022-11-17 14:53 UTC, KornilovVl approved these changes

2022-11-17 14:53 UTC, KornilovVl commented on internal/controllers/NewsletterController.go
>  			http.Error(rw, "Invalid token error, the entered token does not exist", http.StatusBadRequest)
Еще 1 мелкий момент, вот эта ошибка, отобразившись в админке, может ввести пользователя в заблуждение, т.к. он не вводил никаких токенов и понятия не имеет что это такое.
Предлагаю в следующих PR изменить на что-то типа
http.Error(rw, "Access denied", http.StatusNetworkAuthenticationRequired)

2022-11-17 14:56 UTC, tungatarovKl approved these changes

2022-11-17 15:26 UTC, tungatarovKl approved these changes

2022-11-17 16:15 UTC, merged