KU-11 финальные конфиги Docker, настройка постоянного хранилища БД
tungatarovKl/ku1-newsletter-messenger pull request #7
Opened 2022-11-20 08:59 UTC by KornilovVl

Настроил постоянное хранилище данных mysql на хосте 
Написал Dockerfile для mysql для устранения ошибок использования одного docker image и docker volume несколькими сервисами 
Изменил настройки пользователя, бд и пароля

2022-11-20 09:18 UTC, tungatarovKl requested changes

2022-11-20 09:18 UTC, tungatarovKl commented on build-messenger/database/Dockerfile
> +FROM mysql
не очень хорошая идея хранить credentials в dockerfile. Обычно используется 1 докерфайл на прод и тест. В таких случаях можно случайно переопределить credentials для прода. Также не совсем понятно будет где, какие credentials используется.
Обычно такие вещи на проде храниться в более безопасных хранилищах и собираются динамический при деплое. 
Эти credentials можно вынести в .env.example т.к они используется в тестовом окружений. А для прода .env файл собирается отдельно при деплое.

2022-11-20 09:18 UTC, tungatarovKl commented on build-messenger/docker-compose.yml
> +            -   ../../ku1-newsletter-messenger-database:/var/lib/mysql
можно использовать именованные volume'ы. Как тут https://stackoverflow.com/a/45039609

2022-11-22 07:01 UTC, tungatarovKl approved these changes

2022-11-22 07:01 UTC, tungatarovKl commented on build/prod/docker-compose.yml
> +version: '3'
не понял почему удалена dev/docker-compose.yml

2022-11-22 12:19 UTC, KornilovVl commented on build/prod/docker-compose.yml
> +version: '3'
Перенес из build/docker-compose.yml в build/dev/docker-compose.yml . Скорее всего git посчитал файл удаленным а не перенесенным

2022-11-22 14:06 UTC, wildb-ee approved these changes

2022-11-23 03:31 UTC, merged